version: '3.7'

services:
  backend:
    container_name: backend_fastapi
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    env_file:
      - ".env"
    environment:
      - VIRTUAL_HOST=api.fastapi
      - VIRTUAL_PORT=8080

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: db_name
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db:/var/lib/mysql
      - ./.docker/mysqld:/var/run/mysqld

networks:
  default:
    name: nginx-proxy_default
